@startuml

class UsersSchema{
    -userName [PK]: String
    -password: String
    -active [default=true]: boolean
    -createdAt: Date
    -updatedAt: Date
}

class CategoriesSchema{
    -category: String
    -version: String
    -commands: Array
    -owner [id of UsersSchema]: String
    -createdAt: Date
    -updatedAt: Date
    -subCategories: Array
}

note left of CategoriesSchema::commands
    commands is embedded
end note
note left of CategoriesSchema::subCategories
    subCategories is embedded
end note

class commands{
    -command: String
    -language: enum
    -es: String
    -en: String
    -owner [id of UsersSchema]: String
    -createdAt: Date
    -updatedAt: Date
}

class subCategories{
    -createdAt: Date
    -_id: ObjectId
    -updatedAt: Date
    -owner [id of UsersSchema]: String
    -es: String
    -en: String
}

note left of subCategories: 'en' and 'es' are subcategories in their languages

class info_pages{
    -MM-YYYY: string
}    

CategoriesSchema --|> commands: 1:MANY - Embedded
CategoriesSchema --|> subCategories: 1:FEW - Embedded
UsersSchema -[dashed]-> commands
UsersSchema -[dashed]-> subCategories

@enduml